* =======================================
*  HARMONIZATION OF COUNTRIES' NAMES
* ---------------------------------------
*  Federica Cappelli & Nicola Caravaggio
* =======================================

* Database:
* - Climate Change Knowledge Portal, World Bank (WB)
* - FAOSTAT, FAO
* - Freedom House
* - Global Forest Watch
* - Human Development Index, United Nations Development Programme (UNDP)
* - Integrated Network for Societal Conflict Research, Center for Systemic Peace (CSP)
* - International Monetary Fund (IMF)
* - The International Tropical Timber Organization (ITTO)
* - World Development Indicators, World Bank (WB)
* - Worldwide Governance Indicators (Kauffmann and Kraay, 2020)

* Replacement
replace country = "Armenia" if country == "Armenia (from 1992)"
replace country = "Azerbaijan" if country == "Azerbaijan (from 1992)"
replace country = "Bahamas" if country == "Bahamas, The"
replace country = "Belarus" if country == "Belarus (from 1992)"
replace country = "Belgium" if country == "Belgium (from 1998)"
replace country = "Belgium" if country == "Belgium-Luxembourg"
replace country = "Belgium" if country == "Belgium-Luxembourg (to 1997)"
replace country = "Benin" if country == "BÃ©nin"
replace country = "Benin" if country == "Bénin"
replace country = "Bolivia" if country == "Bolivia (Plurinational State of)"
replace country = "Bonaire" if country == "Bonaire (from 2011)"
replace country = "Bosnia and Herzegovina" if country == "Bosnia-Herzegovina"
replace country = "Bosnia and Herzegovina" if country == "Bosnia and Herz."
replace country = "Bosnia and Herzegovina" if country == "Bosnia and Herzegovina (from 1992)"
replace country = "Brunei Darussalam" if country == "Brunei"
replace country = "Cabo Verde" if country == "Cape Verde"
replace country = "Central African Republic" if country == "Central African Rep."
replace country = "China" if country == "China, mainland"
replace country = "Congo, Dem. Rep." if country == "Congo (Democratic Republic of the)"
replace country = "Congo, Dem. Rep." if country == "Congo Kinshasa"
replace country = "Congo, Dem. Rep." if country == "Congo, DR"
replace country = "Congo, Dem. Rep." if country == "Congo, DRC"
replace country = "Congo, Dem. Rep." if country == "Congo-Kinshasa"
replace country = "Congo, Dem. Rep." if country == "Dem. Rep. Congo"
replace country = "Congo, Dem. Rep." if country == "Democratic Republic of the Congo"
replace country = "Congo, Dem. Rep." if country == "Democratic Republic of Congo"
replace country = "Congo, Dem. Rep." if country == "Democratic, DR"
replace country = "Congo, Dem. Rep." if country == "Dem. Rep. of the Congo"
replace country = "Congo, Dem. Rep." if country == "DR Congo"
replace country = "Congo, Rep." if country == "Congo Brazzaville"
replace country = "Congo, Rep." if country == "Congo"
replace country = "Congo, Rep." if country == "Congo-Brazzaville"
replace country = "Congo, Rep." if country == "Republic of Congo"
replace country = "Congo, Rep." if country == "Republic of the Congo"
replace country = "Cote d'Ivoire" if country == "CÃ´te d'Ivoire"
replace country = "Cote d'Ivoire" if country == "Cote d’Ivoire"
replace country = "Cote d'Ivoire" if country == "Côte d'Ivoire"
replace country = "Cote d'Ivoire" if country == "CÃ´te d'Ivoire"
replace country = "Cote d'Ivoire" if country == "C\xf4te d'Ivoire"
replace country = "Croatia" if country == "Croatia (from 1992)"
replace country = "Curacao" if country == "CuraÃ§ao"
replace country = "Curacao" if country == "Curaçao"
replace country = "Curacao" if country == "CuraÃ§ao (from 2010)"
replace country = "Curacao" if country == "Curaçao (from 2010)"
replace country = "Czech Republic" if country == "Czechia"
replace country = "Czech Republic" if country == "Czech Rep."
replace country = "Czech Republic" if country == "Czechia (from 1993)"
replace country = "Czech Republic" if country == "Czechoslovakia (to 1992)"
replace country = "Dominican Republic" if country == "Dominican Rep."
replace country = "Egypt" if country == "Egypt, Arab Rep."
replace country = "Eswatini" if country == "Eswatini (Kingdom of)"
replace country = "Eswatini" if country == "Swaziland"
replace country = "Eritrea" if country == "Eritrea (from 1993)"
replace country = "Estonia" if country == "Estonia (from 1992)"
replace country = "Ethiopia" if country == "Ethiopia PDR"
replace country = "Ethiopia" if country == "Ethiopia (from 1993)"
replace country = "Ethiopia" if country == "Former Ethiopia (to 1992)"
replace country = "French Guiana" if country == "French Guyana"
replace country = "Gambia" if country == "Gambia, The"
replace country = "Gambia" if country == "The Gambia"
replace country = "Georgia" if country == "Georgia (from 1992)"
replace country = "Germany" if country == "Germany (from 1991)"
replace country = "Guyana" if country == "Guyana (British Guiana)"
replace country = "Hong Kong SAR, China" if country == "China, Hong Kong SAR"
replace country = "Hong Kong SAR, China" if country == "Hong Kong"
replace country = "Hong Kong SAR, China" if country == "Hong Kong, China"
replace country = "Hong Kong SAR, China" if country == "Hong Kong, China (SAR)"
replace country = "Iran, Islamic Rep." if country == "Iran (Islamic Republic of)"
replace country = "Iran, Islamic Rep." if country == "Iran (Islamic Rep. of)"
replace country = "Iran, Islamic Rep." if country == "Iran"
replace country = "Kazakhstan" if country == "Kazakhstan (from 1992)"
replace country = "Korea, DPR" if country == "Democratic People's Republic of Korea"
replace country = "Korea, DPR" if country == "Korea, Dem. People�s Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. People�s Rep. "
replace country = "Korea, DPR" if country == "Korea, Dem. People�s Rep. "
replace country = "Korea, DPR" if country == "Korea, Dem. Peoples Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. People's Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. People’s Rep. "
replace country = "Korea, DPR" if country == "Korea, Dem. People's Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. People’s Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. PeopleÕs Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. PeopleÕs Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. PeopleÕs Rep."
replace country = "Korea, DPR" if country == "Dem. People's Rep. of Korea"
replace country = "Korea, DPR" if country == "Korea, Dem. Rep."
replace country = "Korea, DPR" if country == "North Korea"
replace country = "Korea, Rep." if country == "Korea (Republic of)"
replace country = "Korea, Rep." if country == "Korea South"
replace country = "Korea, Rep." if country == "Korea"
replace country = "Korea, Rep." if country == "Korea, Republic of"
replace country = "Korea, Rep." if country == "Republic of Korea"
replace country = "Korea, Rep." if country == "South Korea"
replace country = "Korea, Rep." if country == "Rep. of Korea"
replace country = "Kyrgyzstan" if country == "Kyrgyz Republic"
replace country = "Kyrgyzstan" if country == "Kyrgyzstan (from 1992)"
replace country = "Lao PDR" if country == "Lao People's Democratic Republic"
replace country = "Lao PDR" if country == "Lao People's Dem. Rep."
replace country = "Lao PDR" if country == "Laos"
replace country = "Latvia" if country == "Latvia (from 1992)"
replace country = "Libya" if country == "Libya (Tripolitania, Cyrenaica, Fezzan)"
replace country = "Lithuania" if country == "Lithuania (from 1992)"
replace country = "Luxembourg" if country == "Luxembourg (from 1998)"
replace country = "Macao SAR, China" if country == "China, Macao SAR"
replace country = "Macedonia, FYR" if country == "Macedonia"
replace country = "Macedonia, FYR" if country == "The former Yugoslav Republic of Macedonia"
replace country = "Micronesia, Fed. Sts." if country == "Micronesia"
replace country = "Moldova" if country == "Moldova (Republic of)"
replace country = "Moldova" if country == "Republic of Moldova"
replace country = "Moldova" if country == "Rep. of Moldova (from 1992)"
replace country = "Montenegro" if country == "Montenegro (from 2006)"
replace country = "Myanmar" if country == "Myanmar (Burma)"
replace country = "Netherlands Antilles" if country == "Netherlands Antilles (former)"
replace country = "Netherlands Antilles" if country == "Netherlands Antilles (to 2010)"
replace country = "North Macedonia" if country == "Macedonia, FYR"
replace country = "Reunion" if country == "R\xe9union"
replace country = "Russian Federation" if country == "Russia"
replace country = "Russian Federation" if country == "Russian Federation (from 1992)"
replace country = "Sao Tome and Principe" if country == "SÃ£o TomÃ© and PrÃ­ncipe"
replace country = "Sao Tome and Principe" if country == "SÃ£o TomÃ© and Principe"
replace country = "Sao Tome and Principe" if country == "São Tomé and Principe"
replace country = "Serbia and Montenegro" if country == "Serbia & Montenegro"
replace country = "Serbia and Montenegro" if country == "Serbia & Montenegro *"
replace country = "Serbia and Montenegro" if country == "Serbia and Montenegro (to 2005)"
replace country = "Serbia" if country == "Serbia *"
replace country = "Serbia" if country == "Serbia (from 2006)"
replace country = "Slovak Republic" if country == "Slovakia"
replace country = "Slovak Republic" if country == "Slovakia (from 1993)"
replace country = "Slovenia" if country == "Slovenia (from 1992)"
replace country = "Solomon Islands" if country == "Solomon Is."
replace country = "St. Kitts and Nevis" if country == "Saint Kitts and Nevis"
replace country = "St. Lucia" if country == "Saint Lucia"
replace country = "St. Vincent and the Grenadines" if country == "Saint Vincent and the Grenadines"
replace country = "St. Vincent and the Grenadines" if country == "St. Vincent and Grenadines"
replace country = "St. Vincent and the Grenadines" if country == "St. Vin. and Gren."
replace country = "Sudan" if country == "Sudan (former)"
replace country = "Sudan" if country == "Former Sudan (to 2011)"
replace country = "Sudan" if country == "Sudan (from 2012)"
replace country = "Syrian Arab Republic" if country == "Syria"
replace country = "Syrian Arab Rep." if country == "Syria"
replace country = "Tajikistan" if country == "Tajikistan (from 1992)"
replace country = "Tanzania" if country == "Tanzania (United Rep. of)"
replace country = "Tanzania" if country == "Tanzania (United Republic of)"
replace country = "Tanzania" if country == "United Republic of Tanzania"
replace country = "Timor-Leste" if country == "Timor Leste"
replace country = "Trinidad and Tobago" if country == "Trinidad & Tobago"
replace country = "Turkmenistan" if country == "Turkmenistan (from 1992)"
replace country = "Ukraine" if country == "Ukraine (from 1992)"
replace country = "United Kingdom" if country == "United Kingdom of Great Britain and Northern Ireland"
replace country = "United States" if country == "United States of America"
replace country = "United States" if country == "USA"
replace country = "Uzbekistan" if country == "Uzbekistan (from 1992)"
replace country = "Venezuela" if country == "Venezuela (Bolivarian Republic of)"
replace country = "Venezuela" if country == "Venezuela (Bolivarian Rep. of)"
replace country = "Venezuela" if country == "Venezuela, RB"
replace country = "Vietnam" if country == "Viet Nam"
replace country = "Virgin Islands" if country == "United States Virgin Islands"
replace country = "Virgin Islands" if country == "Virgin Islands (U.S.)"
replace country = "West Bank and Gaza" if country == "Palestine"
replace country = "Yemen" if country == "Yemen, Rep."
replace country = "Yemen" if country == "Yemen (from 1991)"
