* =======================================
*  HARMONIZATION OF COUNTRIES' NAMES
* ---------------------------------------
*  Federica Cappelli & Nicola Caravaggio
* =======================================

* Database:
* - Climate Change Knowledge Portal, World Bank (WB)
* - FAOSTAT, FAO
* - Freedom House
* - Global Forest Watch
* - Human Development Index, United Nations Development Programme (UNDP)
* - Integrated Network for Societal Conflict Research, Center for Systemic Peace (CSP)
* - International Monetary Fund (IMF)
* - World Development Indicators, World Bank (WB)
* - Worldwide Governance Indicators (Kauffmann and Kraay, 2020)

* Replacement
replace country = "Bahamas" if country == "Bahamas, The"
replace country = "Belgium" if country == "Belgium-Luxembourg"
replace country = "Bolivia" if country == "Bolivia (Plurinational State of)"
replace country = "Bosnia and Herzegovina" if country == "Bosnia-Herzegovina"
replace country = "Bosnia and Herzegovina" if country =="Bosnia and Herz."
replace country = "Brunei Darussalam" if country == "Brunei"
replace country = "Cabo Verde" if country == "Cape Verde"
replace country = "Central African Republic" if country =="Central African Rep."
replace country = "China" if country == "China, mainland"
replace country = "Congo, Dem. Rep." if country == "Congo (Democratic Republic of the)"
replace country = "Congo, Dem. Rep." if country == "Congo Kinshasa"
replace country = "Congo, Dem. Rep." if country == "Congo, DR"
replace country = "Congo, Dem. Rep." if country == "Congo, DRC"
replace country = "Congo, Dem. Rep." if country == "Congo-Kinshasa"
replace country = "Congo, Dem. Rep." if country == "Dem. Rep. Congo"
replace country = "Congo, Dem. Rep." if country == "Democratic Republic of the Congo"
replace country = "Congo, Dem. Rep." if country == "Democratic Republic of Congo"
replace country = "Congo, Dem. Rep." if country == "Democratic, DR"
replace country = "Congo, Dem. Rep." if country == "DR Congo"
replace country = "Congo, Rep." if country == "Congo Brazzaville"
replace country = "Congo, Rep." if country == "Congo"
replace country = "Congo, Rep." if country == "Congo-Brazzaville"
replace country = "Congo, Rep." if country == "Republic of Congo"
replace country = "Congo, Rep." if country == "Republic of the Congo"
replace country = "Cote d'Ivoire" if country == "CÃ´te d'Ivoire"
replace country = "Cote d'Ivoire" if country == "Cote d’Ivoire"
replace country = "Cote d'Ivoire" if country == "Côte d'Ivoire"
replace country = "Cote d'Ivoire" if country =="CÃ´te d'Ivoire"
replace country = "Curacao" if country == "CuraÃ§ao"
replace country = "Czech Republic" if country == "Czechia"
replace country = "Czech Republic" if country =="Czech Rep."
replace country = "Dominican Republic" if country == "Dominican Rep."
replace country = "Egypt" if country == "Egypt, Arab Rep."
replace country = "Eswatini" if country == "Eswatini (Kingdom of)"
replace country = "Eswatini" if country == "Swaziland"
replace country = "Ethiopia" if country == "Ethiopia PDR"
replace country = "French Guiana" if country == "French Guyana"
replace country = "Gambia" if country == "Gambia, The"
replace country = "Gambia" if country == "The Gambia"
replace country = "Guyana" if country == "Guyana (British Guiana)"
replace country = "Hong Kong SAR, China" if country == "China, Hong Kong SAR"
replace country = "Hong Kong SAR, China" if country == "Hong Kong"
replace country = "Hong Kong SAR, China" if country == "Hong Kong, China"
replace country = "Hong Kong SAR, China" if country == "Hong Kong, China (SAR)"
replace country = "Iran, Islamic Rep." if country == "Iran (Islamic Republic of)"
replace country = "Iran, Islamic Rep." if country == "Iran"
replace country = "Korea, DPR" if country == "Democratic People's Republic of Korea"
replace country = "Korea, DPR" if country == "Korea, Dem. People�s Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. People�s Rep. "
replace country = "Korea, DPR" if country == "Korea, Dem. People�s Rep. "
replace country = "Korea, DPR" if country == "Korea, Dem. Peoples Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. People's Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. People’s Rep. "
replace country = "Korea, DPR" if country == "Korea, Dem. People's Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. People’s Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. PeopleÕs Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. PeopleÕs Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. PeopleÕs Rep."
replace country = "Korea, DPR" if country == "Korea, Dem. Rep."
replace country = "Korea, DPR" if country == "North Korea"
replace country = "Korea, Rep." if country == "Korea (Republic of)"
replace country = "Korea, Rep." if country == "Korea South"
replace country = "Korea, Rep." if country == "Korea"
replace country = "Korea, Rep." if country == "Korea, Republic of"
replace country = "Korea, Rep." if country == "Republic of Korea"
replace country = "Korea, Rep." if country == "South Korea"
replace country = "Kyrgyzstan" if country == "Kyrgyz Republic"
replace country = "Lao PDR" if country == "Lao People's Democratic Republic"
replace country = "Lao PDR" if country == "Laos"
replace country = "Libya" if country == "Libya (Tripolitania, Cyrenaica, Fezzan)"
replace country = "Macao SAR, China" if country == "China, Macao SAR"
replace country = "Macedonia, FYR" if country == "Macedonia"
replace country = "Macedonia, FYR" if country == "The former Yugoslav Republic of Macedonia"
replace country = "Micronesia, Fed. Sts." if country =="Micronesia"
replace country = "Moldova" if country == "Moldova (Republic of)"
replace country = "Moldova" if country == "Republic of Moldova"
replace country = "Myanmar" if country == "Myanmar (Burma)"
replace country = "Netherlands Antilles" if country == "Netherlands Antilles (former)"
replace country = "North Macedonia" if country == "Macedonia, FYR"
replace country = "Russian Federation" if country == "Russia"
replace country = "Russian Federation" if country == "Russia"
replace country = "Sao Tome and Principe" if country == "SÃ£o TomÃ© and PrÃ­ncipe"
replace country = "Sao Tome and Principe" if country == "SÃ£o TomÃ© and Principe"
replace country = "Sao Tome and Principe" if country == "São Tomé and Principe"
replace country = "Serbia and Montenegro" if country == "Serbia & Montenegro"
replace country = "Serbia and Montenegro" if country == "Serbia & Montenegro *"
replace country = "Serbia" if country == "Serbia *"
replace country = "Slovak Republic" if country == "Slovakia"
replace country = "Slovak Republic" if country == "Slovakia"
replace country = "Solomon Islands" if country == "Solomon Is."
replace country = "St. Kitts and Nevis" if country == "Saint Kitts and Nevis"
replace country = "St. Lucia" if country == "Saint Lucia"
replace country = "St. Vincent and the Grenadines" if country == "Saint Vincent and the Grenadines"
replace country = "St. Vincent and the Grenadines" if country == "St. Vincent and Grenadines"
replace country = "St. Vincent and the Grenadines" if country == "St. Vin. and Gren."
replace country = "Sudan" if country == "Sudan (former)"
replace country = "Syrian Arab Republic" if country == "Syria"
replace country = "Tanzania" if country == "Tanzania (United Republic of)"
replace country = "Tanzania" if country == "United Republic of Tanzania"
replace country = "Timor-Leste" if country == "Timor Leste"
replace country = "Trinidad and Tobago" if country == "Trinidad & Tobago"
replace country = "United States" if country == "United States of America"
replace country = "United States" if country == "USA"
replace country = "Venezuela" if country == "Venezuela (Bolivarian Republic of)"
replace country = "Venezuela" if country == "Venezuela, RB"
replace country = "Vietnam" if country == "Viet Nam"
replace country = "Virgin Islands" if country == "United States Virgin Islands"
replace country = "Virgin Islands" if country == "Virgin Islands (U.S.)"
replace country = "West Bank and Gaza" if country == "Palestine"
replace country = "Yemen" if country == "Yemen, Rep."
