# =======================================
#  HARMONIZATION OF COUNTRIES' NAMES
# ---------------------------------------
#  Federica Cappelli & Nicola Caravaggio
# =======================================

# Database:
# - Climate Change Knowledge Portal, World Bank (WB)
# - FAOSTAT, FAO
# - Freedom House
# - Global Forest Watch
# - Human Development Index, United Nations Development Programme (UNDP)
# - Integrated Network for Societal Conflict Research, Center for Systemic Peace (CSP)
# - International Monetary Fund (IMF)
# - The International Tropical Timber Organization (ITTO)
# - World Development Indicators, World Bank (WB)
# - Worldwide Governance Indicators (Kauffmann and Kraay, 2020)

df$country[df$country == "Armenia (from 1992)"] <- "Armenia" 
df$country[df$country == "Azerbaijan (from 1992)"] <- "Azerbaijan" 
df$country[df$country == "Bahamas, The"] <- "Bahamas" 
df$country[df$country == "Belarus (from 1992)"] <- "Belarus" 
df$country[df$country == "Belgium (from 1998)"] <- "Belgium"
df$country[df$country == "Belgium-Luxembourg"] <- "Belgium"
df$country[df$country == "Belgium-Luxembourg (to 1997)"] <- "Belgium"
df$country[df$country == "BÃ©nin"] <- "Benin"
df$country[df$country == "Bénin"] <- "Benin"
df$country[df$country == "Bolivia (Plurinational State of)"] <- "Bolivia"
df$country[df$country == "Bonaire (from 2011)"] <- "Bonaire"
df$country[df$country == "Bosnia-Herzegovina"] <- "Bosnia and Herzegovina"
df$country[df$country == "Bosnia and Herz."] <- "Bosnia and Herzegovina" 
df$country[df$country == "Bosnia and Herzegovina (from 1992)"] <- "Bosnia and Herzegovina" 
df$country[df$country == "Brunei"] <- "Brunei Darussalam"
df$country[df$country == "Cape Verde"] <- "Cabo Verde"
df$country[df$country == "Central African Rep."] <- "Central African Republic"
df$country[df$country == "China, mainland"] <- "China"
df$country[df$country == "Congo (Democratic Republic of the)"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo Kinshasa"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo, DR"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo, DRC"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo-Kinshasa"] <- "Congo, Dem. Rep."
df$country[df$country == "Dem. Rep. Congo"] <- "Congo, Dem. Rep."
df$country[df$country == "Democratic Republic of the Congo"] <- "Congo, Dem. Rep."
df$country[df$country == "Democratic Republic of Congo"] <- "Congo, Dem. Rep."
df$country[df$country == "Dem. Rep. of the Congo"] <- "Congo, Dem. Rep."
df$country[df$country == "Democratic, DR"] <- "Congo, Dem. Rep."
df$country[df$country == "DR Congo"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo Brazzaville"] <- "Congo, Rep."
df$country[df$country == "Congo"] <- "Congo, Rep."
df$country[df$country == "Congo-Brazzaville"] <- "Congo, Rep."
df$country[df$country == "Republic of Congo"] <- "Congo, Rep."
df$country[df$country == "Republic of the Congo"] <- "Congo, Rep."
df$country[df$country == "CÃ´te d'Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "Cote d’Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "Côte d'Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "CÃ´te d'Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "C\xf4te d'Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "Croatia (from 1992)"] <- "Croatia"
df$country[df$country == "CuraÃ§ao"] <- "Curacao"
df$country[df$country == "Curaçao"] <- "Curacao"
df$country[df$country == "CuraÃ§ao (from 2010)"] <- "Curacao"
df$country[df$country == "Curaçao (from 2010)"] <- "Curacao"
df$country[df$country == "Czechia"] <- "Czech Republic"
df$country[df$country == "Czech Rep."] <- "Czech Republic"
df$country[df$country == "Czechia (from 1993)"] <- "Czech Republic"
df$country[df$country == "Czechoslovakia (to 1992)"] <- "Czech Republic"
df$country[df$country == "Dominican Rep."] <- "Dominican Republic"
df$country[df$country == "Egypt, Arab Rep."] <- "Egypt"
df$country[df$country == "Eswatini (Kingdom of)"] <- "Eswatini"
df$country[df$country == "Swaziland"] <- "Eswatini"
df$country[df$country == "Eritrea (from 1993)"] <- "Eritrea"
df$country[df$country == "Estonia (from 1992)"] <- "Estonia"
df$country[df$country == "Ethiopia PDR"] <- "Ethiopia" 
df$country[df$country == "Ethiopia (from 1993)"] <- "Ethiopia"
df$country[df$country == "Former Ethiopia (to 1992)"] <- "Ethiopia"
df$country[df$country == "French Guyana"] <- "French Guiana"
df$country[df$country == "Gambia, The"] <- "Gambia"
df$country[df$country == "The Gambia"] <- "Gambia"
df$country[df$country == "Georgia (from 1992)"] <- "Georgia"
df$country[df$country == "Germany (from 1991)"] <- "Germany"
df$country[df$country == "Guyana (British Guiana)"] <- "Guyana"
df$country[df$country == "China, Hong Kong SAR"] <- "Hong Kong SAR, China"
df$country[df$country == "Hong Kong"] <- "Hong Kong SAR, China"
df$country[df$country == "Hong Kong, China"] <- "Hong Kong SAR, China"
df$country[df$country == "Hong Kong, China (SAR)"] <- "Hong Kong SAR, China"
df$country[df$country == "Iran (Islamic Republic of)"] <- "Iran, Islamic Rep."
df$country[df$country == "Iran (Islamic Rep. of)"] <- "Iran, Islamic Rep."
df$country[df$country == "Iran"] <- "Iran, Islamic Rep."
df$country[df$country == "Kazakhstan (from 1992)"] <- "Kazakhstan"
df$country[df$country == "Democratic People's Republic of Korea"] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People�s Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People�s Rep. "] <- "Korea, DPR" 
df$country[df$country == "Korea, Dem. People�s Rep. "] <- "Korea, DPR" 
df$country[df$country == "Korea, Dem. Peoples Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People's Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People’s Rep. "] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People's Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People’s Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. PeopleÕs Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. PeopleÕs Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. PeopleÕs Rep."] <- "Korea, DPR"
df$country[df$country == "Dem. People's Rep. of Korea"] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. Rep."] <- "Korea, DPR"
df$country[df$country == "North Korea"] <- "Korea, DPR"
df$country[df$country == "Korea (Republic of)"] <- "Korea, Rep."
df$country[df$country == "Korea South"] <- "Korea, Rep."
df$country[df$country == "Korea"] <- "Korea, Rep." 
df$country[df$country == "Korea, Republic of"] <- "Korea, Rep."
df$country[df$country == "Republic of Korea"] <- "Korea, Rep."
df$country[df$country == "South Korea"] <- "Korea, Rep."
df$country[df$country == "Rep. of Korea"] <- "Korea, Rep."
df$country[df$country == "Kyrgyz Republic"] <- "Kyrgyzstan"
df$country[df$country == "Kyrgyzstan (from 1992)"] <- "Kyrgyzstan"
df$country[df$country == "Lao People's Democratic Republic"] <- "Lao PDR"
df$country[df$country == "Lao People's Dem. Rep."] <- "Lao PDR"
df$country[df$country == "Laos"] <- "Lao PDR"
df$country[df$country == "Latvia (from 1992)"] <- "Latvia"
df$country[df$country == "Libya (Tripolitania, Cyrenaica, Fezzan)"] <- "Libya"
df$country[df$country == "Lithuania (from 1992)"] <- "Lithuania"
df$country[df$country == "Luxembourg (from 1998)"] <- "Luxembourg"
df$country[df$country == "China, Macao SAR"] <- "Macao SAR, China"
df$country[df$country == "Macedonia"] <- "Macedonia, FYR"
df$country[df$country == "The former Yugoslav Republic of Macedonia"] <- "Macedonia, FYR"
df$country[df$country == "Micronesia"] <- "Micronesia, Fed. Sts."
df$country[df$country == "Moldova (Republic of)"] <- "Moldova"
df$country[df$country == "Republic of Moldova"] <- "Moldova"
df$country[df$country == "Rep. of Moldova (from 1992)"] <- "Moldova"
df$country[df$country == "Montenegro (from 2006)"] <- "Montenegro"
df$country[df$country == "Myanmar (Burma)"] <- "Myanmar"
df$country[df$country == "Netherlands Antilles (former)"] <- "Netherlands Antilles"
df$country[df$country == "Netherlands Antilles (to 2010)"] <- "Netherlands Antilles"
df$country[df$country == "Macedonia, FYR"] <- "North Macedonia"
df$country[df$country == "R\xe9union"] <- "Reunion"
df$country[df$country == "Russia"] <- "Russian Federation"
df$country[df$country == "Russian Federation (from 1992)"] <- "Russian Federation"
df$country[df$country == "SÃ£o TomÃ© and PrÃ-ncipe"] <- "Sao Tome and Principe"
df$country[df$country == "SÃ£o TomÃ© and Principe"] <- "Sao Tome and Principe"
df$country[df$country == "São Tomé and Principe"] <- "Sao Tome and Principe"
df$country[df$country == "Serbia & Montenegro"] <- "Serbia and Montenegro"
df$country[df$country == "Serbia & Montenegro *"] <- "Serbia and Montenegro"
df$country[df$country == "Serbia and Montenegro (to 2005)"] <- "Serbia and Montenegro"
df$country[df$country == "Serbia *"] <- "Serbia"
df$country[df$country == "Serbia (from 2006)"] <- "Serbia"
df$country[df$country == "Slovakia"] <- "Slovak Republic"
df$country[df$country == "Slovakia (from 1993)"] <- "Slovak Republic"
df$country[df$country == "Slovenia (from 1992)"] <- "Slovenia"
df$country[df$country == "Solomon Is."] <- "Solomon Islands"
df$country[df$country == "Saint Kitts and Nevis"] <- "St. Kitts and Nevis"
df$country[df$country == "Saint Lucia"] <- "St. Lucia"
df$country[df$country == "Saint Vincent and the Grenadines"] <- "St. Vincent and the Grenadines"
df$country[df$country == "St. Vincent and Grenadines"] <- "St. Vincent and the Grenadines"
df$country[df$country == "St. Vin. and Gren."] <- "St. Vincent and the Grenadines"
df$country[df$country == "Sudan (former)"] <- "Sudan" 
df$country[df$country == "Former Sudan (to 2011)"] <- "Sudan" 
df$country[df$country == "Sudan (from 2012)"] <- "Sudan"
df$country[df$country == "Syria"] <- "Syrian Arab Republic"
df$country[df$country == "Syrian Arab Rep."] <- "Syrian Arab Republic"
df$country[df$country == "Tajikistan (from 1992)"] <- "Tajikistan"
df$country[df$country == "Tanzania (United Rep. of)"] <- "Tanzania"
df$country[df$country == "Tanzania (United Republic of)"] <- "Tanzania"
df$country[df$country == "United Republic of Tanzania"] <- "Tanzania"
df$country[df$country == "Timor Leste"] <- "Timor-Leste"
df$country[df$country == "Trinidad & Tobago"] <- "Trinidad and Tobago"
df$country[df$country == "Turkmenistan (from 1992)"] <- "Turkmenistan"
df$country[df$country == "Ukraine (from 1992)"] <- "Ukraine"
df$country[df$country == "United Kingdom of Great Britain and Northern Ireland"] <- "United Kingdom"
df$country[df$country == "United States of America"] <- "United States"
df$country[df$country == "USA"] <- "United States"
df$country[df$country == "Uzbekistan (from 1992)"] <- "Uzbekistan"
df$country[df$country == "Venezuela (Bolivarian Republic of)"] <- "Venezuela"
df$country[df$country == "Venezuela (Bolivarian Rep. of)"] <- "Venezuela"
df$country[df$country == "Venezuela, RB"] <- "Venezuela"
df$country[df$country == "Viet Nam"] <- "Vietnam"
df$country[df$country == "United States Virgin Islands"] <- "Virgin Islands"
df$country[df$country == "Virgin Islands (U.S.)"] <- "Virgin Islands"
df$country[df$country == "Palestine"] <- "West Bank and Gaza"
df$country[df$country == "Yemen, Rep."] <- "Yemen"
df$country[df$country == "Yemen (from 1991)"] <- "Yemen"
