# =======================================
#  HARMONIZATION OF COUNTRIES' NAMES
# ---------------------------------------
#  Federica Cappelli & Nicola Caravaggio
# =======================================

# Database:
# - Climate Change Knowledge Portal, World Bank (WB)
# - FAOSTAT, FAO
# - Freedom House
# - Global Forest Watch
# - Human Development Index, United Nations Development Programme (UNDP)
# - Integrated Network for Societal Conflict Research, Center for Systemic Peace (CSP)
# - International Monetary Fund (IMF)
# - World Development Indicators, World Bank (WB)
# - Worldwide Governance Indicators (Kauffmann and Kraay, 2020)

df$country[df$country == "Bahamas, The"] <- "Bahamas" 
df$country[df$country == "Belgium-Luxembourg"] <- "Belgium"
df$country[df$country == "Bolivia (Plurinational State of)"] <- "Bolivia"
df$country[df$country == "Bosnia-Herzegovina"] <- "Bosnia and Herzegovina"
df$country[df$country == "Bosnia and Herz."] <- "Bosnia and Herzegovina" 
df$country[df$country == "Brunei"] <- "Brunei Darussalam"
df$country[df$country == "Cape Verde"] <- "Cabo Verde"
df$country[df$country == "Central African Rep."] <- "Central African Republic"
df$country[df$country == "China, mainland"] <- "China"
df$country[df$country == "Congo (Democratic Republic of the)"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo Kinshasa"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo, DR"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo, DRC"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo-Kinshasa"] <- "Congo, Dem. Rep."
df$country[df$country == "Dem. Rep. Congo"] <- "Congo, Dem. Rep."
df$country[df$country == "Democratic Republic of the Congo"] <- "Congo, Dem. Rep."
df$country[df$country == "Democratic Republic of Congo"] <- "Congo, Dem. Rep."
df$country[df$country == "Democratic, DR"] <- "Congo, Dem. Rep."
df$country[df$country == "DR Congo"] <- "Congo, Dem. Rep."
df$country[df$country == "Congo Brazzaville"] <- "Congo, Rep."
df$country[df$country == "Congo"] <- "Congo, Rep."
df$country[df$country == "Congo-Brazzaville"] <- "Congo, Rep."
df$country[df$country == "Republic of Congo"] <- "Congo, Rep."
df$country[df$country == "Republic of the Congo"] <- "Congo, Rep."
df$country[df$country == "CÃ´te d'Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "Cote d’Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "Côte d'Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "CÃ´te d'Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "C\xf4te d'Ivoire"] <- "Cote d'Ivoire"
df$country[df$country == "CuraÃ§ao"] <- "Curacao"
df$country[df$country == "Czechia"] <- "Czech Republic"
df$country[df$country == "Czech Rep."] <- "Czech Republic"
df$country[df$country == "Dominican Rep."] <- "Dominican Republic"
df$country[df$country == "Egypt, Arab Rep."] <- "Egypt"
df$country[df$country == "Eswatini (Kingdom of)"] <- "Eswatini"
df$country[df$country == "Swaziland"] <- "Eswatini"
df$country[df$country == "Ethiopia PDR"] <- "Ethiopia" 
df$country[df$country == "French Guyana"] <- "French Guiana"
df$country[df$country == "Gambia, The"] <- "Gambia"
df$country[df$country == "The Gambia"] <- "Gambia"
df$country[df$country == "Guyana (British Guiana)"] <- "Guyana"
df$country[df$country == "China, Hong Kong SAR"] <- "Hong Kong SAR, China"
df$country[df$country == "Hong Kong"] <- "Hong Kong SAR, China"
df$country[df$country == "Hong Kong, China"] <- "Hong Kong SAR, China"
df$country[df$country == "Hong Kong, China (SAR)"] <- "Hong Kong SAR, China"
df$country[df$country == "Iran (Islamic Republic of)"] <- "Iran, Islamic Rep."
df$country[df$country == "Iran"] <- "Iran, Islamic Rep."
df$country[df$country == "Democratic People's Republic of Korea"] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People�s Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People�s Rep. "] <- "Korea, DPR" 
df$country[df$country == "Korea, Dem. People�s Rep. "] <- "Korea, DPR" 
df$country[df$country == "Korea, Dem. Peoples Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People's Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People’s Rep. "] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People's Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. People’s Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. PeopleÕs Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. PeopleÕs Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. PeopleÕs Rep."] <- "Korea, DPR"
df$country[df$country == "Korea, Dem. Rep."] <- "Korea, DPR"
df$country[df$country == "North Korea"] <- "Korea, DPR"
df$country[df$country == "Korea (Republic of)"] <- "Korea, Rep."
df$country[df$country == "Korea South"] <- "Korea, Rep."
df$country[df$country == "Korea"] <- "Korea, Rep." 
df$country[df$country == "Korea, Republic of"] <- "Korea, Rep."
df$country[df$country == "Republic of Korea"] <- "Korea, Rep."
df$country[df$country == "South Korea"] <- "Korea, Rep."
df$country[df$country == "Kyrgyz Republic"] <- "Kyrgyzstan"
df$country[df$country == "Lao People's Democratic Republic"] <- "Lao PDR"
df$country[df$country == "Laos"] <- "Lao PDR"
df$country[df$country == "Libya (Tripolitania, Cyrenaica, Fezzan)"] <- "Libya"
df$country[df$country == "China, Macao SAR"] <- "Macao SAR, China"
df$country[df$country == "Macedonia"] <- "Macedonia, FYR"
df$country[df$country == "The former Yugoslav Republic of Macedonia"] <- "Macedonia, FYR"
df$country[df$country == "Micronesia"] <- "Micronesia, Fed. Sts."
df$country[df$country == "Moldova (Republic of)"] <- "Moldova"
df$country[df$country == "Republic of Moldova"] <- "Moldova"
df$country[df$country == "Myanmar (Burma)"] <- "Myanmar"
df$country[df$country == "Netherlands Antilles (former)"] <- "Netherlands Antilles"
df$country[df$country == "Macedonia, FYR"] <- "North Macedonia"
df$country[df$country == "R\xe9union"] <- "Reunion"
df$country[df$country == "Russia"] <- "Russian Federation"
df$country[df$country == "Russia"] <- "Russian Federation"
df$country[df$country == "SÃ£o TomÃ© and PrÃ­ncipe"] <- "Sao Tome and Principe"
df$country[df$country == "SÃ£o TomÃ© and Principe"] <- "Sao Tome and Principe"
df$country[df$country == "São Tomé and Principe"] <- "Sao Tome and Principe"
df$country[df$country == "Serbia & Montenegro"] <- "Serbia and Montenegro"
df$country[df$country == "Serbia & Montenegro *"] <- "Serbia and Montenegro"
df$country[df$country == "Serbia *"] <- "Serbia"
df$country[df$country == "Slovakia"] <- "Slovak Republic"
df$country[df$country == "Slovakia"] <- "Slovak Republic"
df$country[df$country == "Solomon Is."] <- "Solomon Islands"
df$country[df$country == "Saint Kitts and Nevis"] <- "St. Kitts and Nevis"
df$country[df$country == "Saint Lucia"] <- "St. Lucia"
df$country[df$country == "Saint Vincent and the Grenadines"] <- "St. Vincent and the Grenadines"
df$country[df$country == "St. Vincent and Grenadines"] <- "St. Vincent and the Grenadines"
df$country[df$country == "St. Vin. and Gren."] <- "St. Vincent and the Grenadines"
df$country[df$country == "Sudan (former)"] <- "Sudan" 
df$country[df$country == "Syria"] <- "Syrian Arab Republic"
df$country[df$country == "Tanzania (United Republic of)"] <- "Tanzania"
df$country[df$country == "United Republic of Tanzania"] <- "Tanzania"
df$country[df$country == "Timor Leste"] <- "Timor-Leste"
df$country[df$country == "Trinidad & Tobago"] <- "Trinidad and Tobago"
df$country[df$country == "United States of America"] <- "United States"
df$country[df$country == "USA"] <- "United States"
df$country[df$country == "Venezuela (Bolivarian Republic of)"] <- "Venezuela"
df$country[df$country == "Venezuela, RB"] <- "Venezuela"
df$country[df$country == "Viet Nam"] <- "Vietnam"
df$country[df$country == "United States Virgin Islands"] <- "Virgin Islands"
df$country[df$country == "Virgin Islands (U.S.)"] <- "Virgin Islands"
df$country[df$country == "Palestine"] <- "West Bank and Gaza"
df$country[df$country == "Yemen, Rep."] <- "Yemen"